---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 2021hackathon.azurecr.io/frontend-nginx:latest
        ports:
        - containerPort: 80
        
        # volumeMounts:
      #  volumeMounts:
       # - name: config
        #  mountPath: "/etc/nginx/conf.d"
         # readOnly: true
     
    #  volumes:
     #   # You set volumes at the Pod level, then mount them into containers inside that Pod
      #  - name: config
       #   configMap:
        #    # Provide the name of the ConfigMap you want to mount.
         #   name: nginx-paths
